var classes = [
    { id: 1, subject: 'Mathematics', location: 'Barnet', price: 200, spaces: 5, image: "images/mathematics.png" },
    { id: 2, subject: 'English Language', location: 'Hendon', price: 100, spaces: 5, image: "images/english.png" },
    { id: 3, subject: 'Computer Science', location: 'Burnt Oak', price: 500, spaces: 5, image: "images/ComputerScience.png" },
    { id: 4, subject: 'Business Studies', location: 'Addington', price: 50, spaces: 5, image: "images/BusinessStudies.png" },
    { id: 5, subject: 'Chemistry', location: 'Colindale', price: 150, spaces: 5, image: "images/chemistry.png" },
    { id: 6, subject: 'Physics', location: 'Finchley', price: 20, spaces: 5, image: "images/physics.png" },
    { id: 7, subject: 'Biology', location: 'Wembley', price: 400, spaces: 5, image: "images/biology.png" },
    { id: 8, subject: 'Sociology', location: 'Tottenham', price: 10, spaces: 5, image: "images/sociology.png" },
    { id: 9, subject: 'Economics', location: 'Edgware', price: 25, spaces: 5, image: "images/economics.png" },
    { id: 10, subject: 'Geography', location: 'Highbury', price: 45, spaces: 5, image: "images/geography.png" },
    { id: 11, subject: 'Music', location: 'Acton', price: 5, spaces: 5, image: "images/music.png" },
    { id: 12, subject: 'Literature', location: 'Highgate', price: 1, spaces: 5, image: "images/literature.png" },
    { id: 13, subject: 'Physical Education', location: 'Kenton', price: 250, spaces: 5, image: "images/PhysicalEducation.png" },
    { id: 14, subject: 'Art and Design', location: 'Mill Hill', price: 450, spaces: 5, image: "images/ArtandDesign.jpg" },
    { id: 15, subject: 'Computing', location: 'Seven Kings', price: 1000, spaces: 5, image: "images/computing.png" },
    { id: 16, subject: 'History', location: 'Beckenham', price: 35, spaces: 5, image: "images/history.png" },
    { id: 17, subject: 'Psychology', location: 'New Beckenham', price: 1500, spaces: 5, image: "images/psychology.png" },
    { id: 18, subject: 'Drama', location: 'Upperhill', price: 200, spaces: 5, image: "images/drama.png" },
    { id: 19, subject: 'French', location: 'Turfnell Park', price: 2000, spaces: 5, image: "images/french.png" },
    { id: 20, subject: 'German', location: 'The Borough', price: 2500, spaces: 5, image: "images/german.png" },
];