var classes = [
    { id: 1, subject: 'Mathematics', location: 'Barnet', price: 200, spaces: 5, image: "images/mathematics.png", fontAwesomeIcon: "fa-solid fa-square-root-variable" },
    { id: 2, subject: 'English Language', location: 'Hendon', price: 100, spaces: 5, image: "images/english.png", fontAwesomeIcon: "fa-solid fa-pen-nib" },
    { id: 3, subject: 'Computer Science', location: 'Burnt Oak', price: 500, spaces: 5, image: "images/ComputerScience.png", fontAwesomeIcon: "fa-solid fa-computer" },
    { id: 4, subject: 'Business Studies', location: 'Addington', price: 50, spaces: 5, image: "images/BusinessStudies.png", fontAwesomeIcon: "fa-solid fa-business-time" },
    { id: 5, subject: 'Chemistry', location: 'Colindale', price: 150, spaces: 5, image: "images/chemistry.png", fontAwesomeIcon: "fa-solid fa-flask-vial" },
    { id: 6, subject: 'Physics', location: 'Finchley', price: 20, spaces: 5, image: "images/physics.png", fontAwesomeIcon: "fa-solid fa-wheelchair-move" },
    { id: 7, subject: 'Biology', location: 'Wembley', price: 400, spaces: 5, image: "images/biology.png", fontAwesomeIcon: "fa-solid fa-dna" },
    { id: 8, subject: 'Sociology', location: 'Tottenham', price: 10, spaces: 5, image: "images/sociology.png", fontAwesomeIcon: "fa-solid fa-book-open-reader" },
    { id: 9, subject: 'Economics', location: 'Edgware', price: 25, spaces: 5, image: "images/economics.png", fontAwesomeIcon: "fa-solid fa-calculator" },
    { id: 10, subject: 'Geography', location: 'Highbury', price: 45, spaces: 5, image: "images/geography.png", fontAwesomeIcon: "fa-solid fa-book-atlas" },
    { id: 11, subject: 'Music', location: 'Acton', price: 5, spaces: 5, image: "images/music.png", fontAwesomeIcon: "fa-solid fa-music" },
    { id: 12, subject: 'Literature', location: 'Highgate', price: 1, spaces: 5, image: "images/literature.png", fontAwesomeIcon: "fa-solid fa-book-open" },
    { id: 13, subject: 'Physical Education', location: 'Kenton', price: 250, spaces: 5, image: "images/PhysicalEducation.png", fontAwesomeIcon: "fa-solid fa-dumbbell" },
    { id: 14, subject: 'Art and Design', location: 'Mill Hill', price: 450, spaces: 5, image: "images/ArtandDesign.jpg", fontAwesomeIcon: "fa-solid fa-palette" },
    { id: 15, subject: 'Computing', location: 'Seven Kings', price: 1000, spaces: 5, image: "images/computing.png", fontAwesomeIcon: "fa-solid fa-laptop" },
    { id: 16, subject: 'History', location: 'Beckenham', price: 35, spaces: 5, image: "images/history.png", fontAwesomeIcon: "fa-solid fa-earth-africa" },
    { id: 17, subject: 'Psychology', location: 'New Beckenham', price: 1500, spaces: 5, image: "images/psychology.png", fontAwesomeIcon: "fa-solid fa-brain" },
    { id: 18, subject: 'Drama', location: 'Upperhill', price: 200, spaces: 5, image: "images/drama.png", fontAwesomeIcon: "fa-solid fa-people-carry-box" },
    { id: 19, subject: 'French', location: 'Turfnell Park', price: 2000, spaces: 5, image: "images/french.png", fontAwesomeIcon: "fa-solid fa-globe" },
    { id: 20, subject: 'German', location: 'The Borough', price: 2500, spaces: 5, image: "images/german.png", fontAwesomeIcon: "fa-solid fa-globe" },
];